name: Benchmark

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Cache hyperfine
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-hyperfine
          restore-keys: |
            ${{ runner.os }}-hyperfine-

      - name: Install hyperfine (if not cached)
        run: |
          if [ ! -f ~/.cargo/bin/hyperfine ]; then
            cargo install hyperfine
          fi

      - name: Build projects
        run: |
          ls -l
          for project in $(ls -d day_*); do
            cd $project
            cargo build --release
          done

      - name: Run benchmarks with hyperfine
        run: |
          ls -l
          for project in $(ls -d day_*); do
            cd $project
            hyperfine ./target/release/$project --export-markdown benchmark-results.md 
          done
