name: Benchmark

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install hyperfine
        run: |
          cargo install hyperfine

      - name: Find changed projects
        id: changed-projects
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} HEAD)
          CHANGED_PROJECTS=$(echo "$CHANGED_FILES" | grep -E 'day_[0-9]+' | awk -F/ '{print $1}')
          echo "changed_projects=$CHANGED_PROJECTS" >> $GITHUB_OUTPUT

      - name: Build projects
        run: |
          for project in $(ls -d day_*); do # Loop through all day_* directories
            cd $project
            cargo build --release
          done

      - name: Run benchmarks with hyperfine
        run: |
          for project in $(ls -d day_*); do
            cd $project
            hyperfine ./target/release/$project --export-markdown benchmark-results.md 
          done
